#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
