#!/usr/bin/env bash
# Bash script that installs haproxy

apt-get -y update
apt-get -y install haproxy

CONF="\
frontend main
         bind *:80
         mode http
         default_backend web-server
backend web-server
        balance roundrobin
        server 2621-web-01 34.138.154.248:80
        server 2621-web-02 35.227.26.227:80
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
service haproxy restart
