#!/usr/bin/env bash
# gives you information about the holbertonschool file.
file="holbertonschool"
if [ -e "$file" ]
then
    echo $file "file exists"
    if [ -f "$file" ]
    then
        echo $file "is a regular file"
        fi
    if [ -s "$file" ]
    then
        echo $file "file is not empty"
    else
        echo $file "file is empty"
    fi
else
    echo "$file does not exist"
fi
