#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
chown -R nginx:nginx /etc/nginx/
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
