#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
echo 'user nginx;' >> /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
